adding parameter support to docker rule
itzg/junit-rule-docker pull request #1
Opened 2017-09-12 09:58 UTC by sanados

a lot of docker images need configuration on startup
that you normally add to docker run -e ....
added this support in as the official elasticsearch docker images have xpack which force auth.

2017-09-13 00:36 UTC, itzg requested changes
Thank you so much @sanados for this contribution. The main changes look perfect and I just have a few test related requests.

2017-09-13 00:36 UTC, itzg commented on src/test/java/me/itzg/testing/DockerRuleTestElasticsearch.java
> +public class DockerRuleTestElasticsearch {
Please rename this to end with "Test" so that Maven-surefire will pick it up. So it would be `DockerRuleElasticsearchTest`.

2017-09-13 00:36 UTC, itzg commented on src/test/java/me/itzg/testing/DockerRuleTestElasticsearch.java
> +			assertEquals(jsonResponse, "{\"_all\":{\"primaries\":{\"docs\":{\"count\":0,\"deleted\":0},\"store\":{\"size_in_bytes\":324,\"throttle_time_in_millis\":0},\"indexing\":{\"index_total\":0,\"index_t
This seems like a brittle assertion...and in fact it failed when I ran it. I never could narrow down which specific bit differed. I would suggest you instead do some spot assertions of fields within the `indicesStatsResponse` object itself.

2017-09-13 00:36 UTC, itzg commented on src/test/java/me/itzg/testing/DockerRuleTestElasticsearch.java
> +	public void testDocker() throws DockerCertificateException, DockerException, InterruptedException {
I'm guessing this was here to do some sanity testing of things. I think you can remove it since the rule itself does a pull.

2017-09-13 04:14 UTC, sanados commented
Very good points, I adjusted the pull request.

2017-09-13 22:30 UTC, itzg approved these changes

2017-09-13 22:30 UTC, merged

2017-09-14 01:25 UTC, itzg commented
FYI, your change is now included in 1.3 and is published to https://jcenter.bintray.com

2017-09-14 04:01 UTC, sanados commented
thx!